Repository ti-broish/results, pull requests merged in 2023-03, with the labels that each got.

#68 Add risk sections to map, change initial map mode state
  src/components/ResultUnit.js
  src/components/ViolationFeeds.js
  src/components/Violations.js
  src/components/components/bulgaria_map/BulgariaMap.js
  src/components/components/bulgaria_map/generateRegionData.js
  src/components/components/bulgaria_map/generateTooltipContent.js
  src/components/components/bulgaria_map/helpers/index.js
  src/components/components/subdivision_table/SubdivisionTable.js
  src/components/components/subdivision_table/SubdivisionTableRow.js
  src/components/components/subdivision_table/sortSubdivisionTable.js
  src/components/embeds/MiniResultsGlobal.js
  src/components/units/Aggregation.js
  src/components/units/Section.js
  src/components/units/helpers/index.js
Labels: резултати

#73 refactor: Map controls
  src/components/components/bulgaria_map/BulgariaMap.js
  src/components/components/bulgaria_map/helpers/index.js
  src/components/units/Aggregation.js
Labels: карта, резултати

#72 Upload photos
  src/components/UploadPhotos.js
  src/components/ViolationForm.js
  src/components/sectionSelector/SectionSelector.js
  src/utils/fileToBase64.js
  src/utils/uploadPhotosHelper.js
Labels: сигнали

#81 Set explicit value for RFM when changing state dynamically
  src/components/ViolationForm.js
  src/components/sectionSelector/DropDown.js
  src/components/sectionSelector/SectionSelector.js
Labels: проблем, сигнали

#78 Creates form for Protocol sending
  package-lock.json
  package.json
  src/components/Election.js
  src/components/ProtocolForm.js
  src/components/UploadPhotos.js
  src/components/ViolationForm.js
  src/utils/ValidationError.js
  src/utils/api.js
  src/utils/uploadPhotosHelper.js
Labels: протоколи

#84 Добавяне на recaptcha при изпращане на сигнал/протокол
  .env
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  src/components/App.js
  src/components/ProtocolForm.js
  src/components/ViolationForm.js
  webpack/base.config.js
Labels: резултати

#82 Fix validation violation form
  package-lock.json
  package.json
  src/components/ViolationForm.js
  src/components/sectionSelector/DropDown.js
  src/components/sectionSelector/Radios.js
  src/components/sectionSelector/SectionSelector.js
Labels: сигнали

#90 Добавяне на email към протокол след изпращане
  src/components/ProtocolForm.js
  src/components/UploadPhotos.js
Labels: протоколи

#93 Show list of submitted protocols and violations
  src/components/Election.js
  src/components/MyProtocols.js
  src/components/MyViolations.js
  src/components/ProtocolForm.js
  src/components/ProtocolSummary.js
  src/components/ResultUnit.js
  src/components/Submit.js
  src/components/ViolationForm.js
  src/components/routes.js
  src/utils/api.js
Labels: сигнали, протоколи

#95 Подобрения по UI на формите
  src/components/ViolationForm.js
  src/components/sectionSelector/Radios.js
Labels: сигнали, резултати

#96 Show but disable protocol submit button until enough images
  src/components/ProtocolForm.js
Labels: протоколи

#98 Подобрения по линкове и бутони
  src/components/App.js
  src/components/ProtocolForm.js
  src/components/Submit.js
  src/components/ViolationForm.js
  src/components/components/Button.js
  src/components/components/Link.js
Labels: сигнали, протоколи

#99 Support filtering town/section in violation form with 3-digit county code
  src/components/sectionSelector/SectionSelector.js
Labels: сигнали

#103 Подобрения по мобилния изглед и формите
  src/components/App.js
  src/components/ProtocolForm.js
  src/components/ViolationForm.js
  src/components/components/Button.js
  src/components/components/Input.js
  src/components/components/Label.js
  src/components/components/Select.js
  src/components/components/Textarea.js
  src/components/sectionSelector/DropDown.js
  src/index.ejs
Labels: сигнали, протоколи

#107 Show server validation message if available
  src/components/ViolationForm.js
  src/components/sectionSelector/SectionSelector.js
  src/utils/api.js
Labels: сигнали

#108 Качване на снимките преди изпращането на цялата форма
  package-lock.json
  package.json
  src/components/ProtocolForm.js
  src/components/UploadPhotos.js
  src/components/ViolationForm.js
  src/utils/fileToBase64.js
  src/utils/uploadPhotosHelper.js
Labels: сигнали, протоколи

#111 Показване на всички партии в страницата на секцията
  src/components/components/ResultsLine.js
  src/components/components/bulgaria_map/BulgariaMap.js
  src/components/components/bulgaria_map/generateRegionData.js
  src/components/components/bulgaria_map/generateTooltipContent.js
  src/components/components/results_table/ResultsTable.js
  src/components/components/results_table/ResultsTableRow.js
  src/components/layout/Header.js
  src/components/units/Section.js
Labels: карта, резултати
